import { Question } from "./types"

export const questions: Question[] = [
  {
    id: 1,
    tema: "Princípios Institucionais",
    dif: "baixa",
    prob: "alta",
    enunc: "Segundo o art. 1º da Lei nº 883/2005, a Polícia Civil é definida como:",
    ops: [
      "Instituição permanente, essencial à função jurisdicional do Estado, incumbindo-lhe, com exclusividade, as funções de polícia judiciária.",
      "Instituição permanente, estruturada em carreira, essencial à preservação da ordem pública e da incolumidade das pessoas e do patrimônio, incumbindo-lhe as funções de polícia judiciária e a apuração de infrações penais, exceto as militares.",
      "Órgão de segurança pública, responsável pela defesa da ordem pública e manutenção da segurança interna, com atuação complementar à Polícia Militar.",
      "Instituição auxiliar do Ministério Público, incumbida de investigações criminais e da execução de mandados judiciais.",
      "Força auxiliar do Exército, mantida pelo Estado, responsável por ações de policiamento ostensivo.",
    ],
    corr: 1,
    com: "A definição completa do art. 1º inclui o termo 'estruturada em carreira', que é distintivo. As alternativas A e C confundem com outras funções de polícia (ostensiva/preventiva). A D confunde com o MP e a E com a PM.",
    art: "Art. 1º",
  },
  {
    id: 2,
    tema: "Princípios Institucionais",
    dif: "media",
    prob: "alta",
    enunc: "A função de Polícia Judiciária, segundo a Lei nº 883/2005, tem como missão específica:",
    ops: [
      "A fiscalização do cumprimento das penas restritivas de direitos e da liberdade condicional.",
      "A investigação das infrações penais e a instrução de procedimentos administrativos contra militares estaduais.",
      "A investigação e apuração das infrações penais, a identificação civil e criminal e o fornecimento de dados ao sistema de Justiça Criminal.",
      "A orientação e fiscalização do trânsito urbano e a lavratura de autos de infração no interior do Estado.",
      "A proteção de autoridades e dignitários e a segurança das instalações do Poder Judiciário Estadual.",
    ],
    corr: 2,
    com: "O art. 3º define que a função de Polícia Judiciária compreende: (I) investigação e apuração de infrações penais; (II) identificação civil e criminal; (III) fornecimento de dados ao sistema de Justiça Criminal.",
    art: "Art. 3º",
  },
  {
    id: 3,
    tema: "Princípios Institucionais",
    dif: "media",
    prob: "alta",
    enunc: "A atuação da Polícia Civil é regida por quais princípios, conforme o art. 4º da Lei nº 883/2005?",
    ops: [
      "Moralidade, Publicidade, Autotutela e Subsidiariedade.",
      "Legalidade, Impessoalidade, Moralidade, Publicidade, Eficiência, Razoabilidade, Unidade, Indivisibilidade, Autonomia Funcional e Hierarquia.",
      "Apenas Legalidade, Moralidade e Eficiência, aplicando-se subsidiariamente os princípios da Administração Federal.",
      "Discricionariedade, Oportunidade e Presunção de Inocência.",
      "Oficialidade, Oficiosidade e Indisponibilidade da Ação Penal.",
    ],
    corr: 1,
    com: "O art. 4º lista os 10 princípios reitores: Legalidade, Impessoalidade, Moralidade, Publicidade, Eficiência, Razoabilidade, Unidade, Indivisibilidade, Autonomia Funcional e Hierarquia. A alternativa A omite vários princípios e inclui Autotutela/Subsidiariedade que não constam.",
    art: "Art. 4º",
  },
  {
    id: 4,
    tema: "Princípios Institucionais",
    dif: "alta",
    prob: "alta",
    enunc: "Analise as assertivas sobre os direitos e deveres do servidor policial civil:\nI. É dever do servidor policial civil atender às requisições legais do Poder Judiciário e Ministério Público.\nII. É direito do servidor policial civil portar arma de fogo, mesmo quando de folga, observados os regulamentos.\nIII. O servidor pode recusar cumprimento de ordem manifestamente ilegal.\nIV. É vedado ao servidor policial civil participar de sociedade comercial, exceto como acionista.",
    pergunta: "Estão corretas:",
    ops: [
      "Apenas I, II e III.",
      "I, II, III e IV.",
      "Apenas I e IV.",
      "Apenas II e III.",
      "Apenas I, III e IV.",
    ],
    corr: 1,
    com: "Todas as assertivas estão corretas: I (art. 5º, X); II (art. 6º, III); III (art. 5º, XI); IV (art. 8º, VI - é vedado participar de sociedade comercial, exceto como acionista, quotista ou comanditário).",
    art: "Arts. 5º, 6º e 8º",
  },
  {
    id: 5,
    tema: "Princípios Institucionais",
    dif: "media",
    prob: "alta",
    enunc: "Sobre os deveres do servidor policial civil, é INCORRETO afirmar que:",
    ops: [
      "Deve manter residência na localidade onde exerce suas funções, salvo autorização superior.",
      "Deve frequentar cursos e treinamentos de atualização e capacitação profissional.",
      "Pode eximir-se de responder a perguntas da imprensa sobre assuntos oficiais.",
      "Pode filiar-se a partidos políticos, mas deve exercer atividade político-partidária no ambiente de trabalho.",
      "Deve observar as normas legais e regulamentares.",
    ],
    corr: 3,
    com: "O art. 8º, IX veda a participação em atividade político-partidária no ambiente de trabalho, tornando a alternativa D INCORRETA. As demais assertivas estão corretas: A (art. 5º, VIII), B (art. 5º, XIV), C (art. 5º, IX - deve encaminhar à autoridade competente).",
    art: "Art. 8º, IX",
  },
  {
    id: 6,
    tema: "Direitos e Deveres",
    dif: "baixa",
    prob: "alta",
    enunc: "São direitos assegurados ao servidor policial civil, EXCETO:",
    ops: [
      "Porte de arma de fogo, ainda quando de folga, observados os regulamentos.",
      "Prisão especial ou sala especial de Estado-Maior quando preso antes da condenação definitiva.",
      "Uso de documento de identidade policial com validade em todo o território nacional.",
      "Isenção total de pagamento de passagens e pedágios em viagens a serviço.",
      "Prisão somente em flagrante delito, ou por ordem escrita de autoridade judicial competente.",
    ],
    corr: 3,
    com: "A alternativa D não consta no art. 6º como direito do servidor policial. Os demais direitos são expressamente previstos: A (inciso III), B (inciso IV), C (inciso II - carteira funcional com validade nacional) e E (inciso VII).",
    art: "Art. 6º",
  },
  {
    id: 7,
    tema: "Direitos e Deveres",
    dif: "media",
    prob: "alta",
    enunc: "Nos termos da Lei nº 883/2005, a função de investigação policial civil tem caráter:",
    ops: [
      "Exclusivamente administrativo, sob supervisão direta do Ministério Público.",
      "Técnico-científico, sendo competência privativa dos servidores policiais civis de cargo efetivo.",
      "Misto, podendo ser delegada a peritos autônomos contratados pelo Estado.",
      "Auxiliar, exercida sob a direção de magistrado do inquérito.",
      "Facultativo, permitindo-se a atuação de particulares na coleta de provas.",
    ],
    corr: 1,
    com: "O art. 7º define que a função de investigação tem caráter técnico-científico, sendo 'competência privativa dos servidores policiais civis de cargo efetivo'. Inclui análise e descrição de cenários, circunstâncias e condutas criminais, busca da perfeição técnica dos atos do inquérito policial.",
    art: "Art. 7º",
  },
  {
    id: 8,
    tema: "Atribuições da Polícia Civil",
    dif: "baixa",
    prob: "media",
    enunc: "O dia consagrado à Polícia Civil do Estado do Amapá, nos termos do art. 9º da Lei nº 883/2005, é:",
    ops: [
      "7 de setembro.",
      "23 de março.",
      "21 de abril.",
      "15 de novembro.",
      "2 de julho.",
    ],
    corr: 2,
    com: "O art. 9º da Lei nº 883/2005 estabelece: 'O dia 21 de abril será consagrado à Polícia Civil do Estado do Amapá.' Não confundir com a data de promulgação da lei (23 de março de 2005).",
    art: "Art. 9º",
  },
  {
    id: 9,
    tema: "Estrutura Organizacional",
    dif: "media",
    prob: "alta",
    enunc: "A estrutura da Polícia Civil do Estado do Amapá, conforme o art. 10 da Lei nº 883/2005, compreende os seguintes órgãos:",
    ops: [
      "Conselho Superior, Corregedoria, Departamentos Operacionais e Gabinete do Delegado Geral.",
      "Órgãos Superiores de Deliberação Colegiada; Órgãos de Direção Superior; Órgão de Formação e Capacitação Profissional; Órgão de Assessoramento e Apoio Técnico-Administrativo; e Órgãos de Execução Programática.",
      "Órgãos de Direção, Órgãos de Controle Interno, Órgãos de Execução e Órgãos de Apoio Logístico.",
      "Delegacia Geral, Corregedoria, Departamentos e Unidades Policiais.",
      "Órgãos Superiores, Órgãos Intermediários e Órgãos de Base.",
    ],
    corr: 1,
    com: "O art. 10 enumera os 5 componentes da estrutura: I-Órgãos Superiores de Deliberação Colegiada; II-Órgãos de Direção Superior; III-Órgão de Formação e Capacitação Profissional; IV-Órgão de Assessoramento e Apoio Técnico-Administrativo; V-Órgãos de Execução Programática.",
    art: "Art. 10",
  },
  {
    id: 10,
    tema: "Estrutura Organizacional",
    dif: "media",
    prob: "alta",
    enunc: "O Conselho Superior da Polícia Civil, nos termos da Lei nº 883/2005, é presidido por qual autoridade e qual é a natureza do órgão?",
    ops: [
      "Presidido pelo Secretário de Justiça; é órgão deliberativo e fiscalizador.",
      "Presidido pelo Delegado Geral de Polícia Civil; é órgão consultivo, normativo e deliberativo para fins de controle do ingresso, estágio probatório, remoção, promoção, hierarquia e regime disciplinar.",
      "Presidido pelo Corregedor-Geral; é órgão exclusivamente disciplinar.",
      "Presidido pelo Delegado mais antigo da Classe Especial; é órgão deliberativo de carreira.",
      "Presidido pelo Governador do Estado; é órgão superior de supervisão institucional.",
    ],
    corr: 1,
    com: "O art. 12 define: 'O Conselho Superior da Polícia Civil, órgão consultivo, normativo e deliberativo, para fins de controle do ingresso, estágio probatório, remoção, promoção, hierarquia e regime disciplinar das carreiras policiais civis', sendo presidido pelo Delegado Geral (inciso I).",
    art: "Art. 12",
  },
  {
    id: 11,
    tema: "Estrutura Organizacional",
    dif: "alta",
    prob: "alta",
    enunc: "Analise as assertivas sobre o Conselho Superior de Polícia Civil (CSPC):\nI. Compete ao CSPC julgar o estágio probatório de policial civil.\nII. O CSPC pode deliberar sobre remoção de servidores policiais no interesse do serviço.\nIII. As deliberações do CSPC são adotadas pelo voto de 2/3 de seus membros, consignadas em resoluções.\nIV. Compete ao CSPC compor, mediante sorteio, as Câmaras Disciplinares.",
    pergunta: "Estão corretas apenas:",
    ops: [
      "I e III.",
      "I, II e IV.",
      "II e IV.",
      "I, II, III e IV.",
      "III e IV.",
    ],
    corr: 1,
    com: "I-CORRETA (art. 13, IV); II-CORRETA (art. 13, IX); III-INCORRETA — as deliberações são por maioria simples, não 2/3 (art. 13, §2º); IV-CORRETA (art. 13, XIII). Portanto: I, II e IV.",
    art: "Art. 13",
  },
  {
    id: 12,
    tema: "Estrutura Organizacional",
    dif: "alta",
    prob: "alta",
    enunc: "As Câmaras Disciplinares previstas na Lei nº 883/2005 são:",
    ops: [
      "Compostas por 3 membros Delegados da Classe Especial, com mandato de 2 anos.",
      "Compostas por 5 membros, todos designados mediante sorteio, presididas por membro titular do Conselho Superior, às quais não concorrem o presidente e o vice-presidente do CSPC.",
      "Compostas por 7 membros, sendo 3 do CSPC e 4 de entidades de classe.",
      "Compostas por 5 membros eleitos pelos policiais civis, com mandato de 1 ano, vedada a recondução.",
      "Compostas por 3 membros do CSPC e 2 representantes do MP, com mandato de 2 anos.",
    ],
    corr: 1,
    com: "O art. 14 dispõe: Câmaras Disciplinares compostas por 5 membros, todos designados mediante sorteio, presididas por membro titular do Conselho Superior — sem participar o presidente (Delegado Geral) e o vice-presidente (Corregedor-Geral). Mandatos de 1 ano, podendo ser reconduzidos por igual período (§2º).",
    art: "Art. 14",
  },
  {
    id: 13,
    tema: "Estrutura Organizacional",
    dif: "alta",
    prob: "alta",
    enunc: "Quando a Câmara Disciplinar entender pela aplicação das penas de demissão, cassação de aposentadoria e disponibilidade, divergindo da proposição da autoridade disciplinar:",
    ops: [
      "A Câmara aplica a pena diretamente, sem necessidade de recurso.",
      "A decisão final será do Secretário de Justiça e Segurança Pública.",
      "A Câmara encaminhará recurso ex-offício ao Conselho Superior da Polícia Civil.",
      "O Delegado Geral decidirá sobre a pena a aplicar, ouvida a Câmara.",
      "Os autos são devolvidos à autoridade disciplinar para reconsideração.",
    ],
    corr: 2,
    com: "Art. 14, §4º: 'Quando a Câmara entender pela aplicação das penas de demissão, cassação de aposentadoria e disponibilidade, divergindo da proposição da autoridade disciplinar, encaminhará recurso ex-offício ao Conselho Superior da Polícia Civil.' O recurso é automático, independente de requerimento.",
    art: "Art. 14, §4º",
  },
  {
    id: 14,
    tema: "Estrutura Organizacional",
    dif: "media",
    prob: "alta",
    enunc: "Sobre a competência do Delegado Geral de Polícia Civil para avocar inquérito policial, nos termos do art. 17 da Lei nº 883/2005:",
    ops: [
      "É ordinária e de exercício rotineiro, sem necessidade de fundamentação.",
      "É excepcional, fundamentada e restrita a inquéritos que já tenham sido remetidos ao Ministério Público.",
      "É excepcional e fundamentada, cabível em relação a inquérito policial, termo circunstanciado e procedimento especial instaurado, para exame e redistribuição.",
      "É plena e irrestrita, podendo ser exercida a qualquer tempo e sem qualquer motivação.",
      "É vedada após o prazo de 30 dias da instauração do inquérito.",
    ],
    corr: 2,
    com: "O art. 17, VIII dispõe que o Delegado Geral pode 'Avocar, excepcional e fundamentadamente, inquérito policial, termo circunstanciado e procedimento especial instaurado, para exame e redistribuição'. A avocação exige excepcionalidade e fundamentação — não é ato ordinário nem irrestrito.",
    art: "Art. 17, VIII",
  },
  {
    id: 15,
    tema: "Estrutura Organizacional",
    dif: "alta",
    prob: "alta",
    enunc: "À Corregedoria Geral da Polícia Civil, nos termos do art. 18 da Lei nº 883/2005, NÃO compete:",
    ops: [
      "Promover a apuração das infrações penais e transgressões disciplinares atribuídas a policiais civis.",
      "Avocar e realizar os serviços de correição em caráter permanente e extraordinário.",
      "Exercer o controle externo da atividade policial civil em substituição ao Ministério Público.",
      "Dirimir os conflitos de competência entre unidades policiais.",
      "Receber queixas ou representações sobre faltas cometidas por servidores policiais civis.",
    ],
    corr: 2,
    com: "A Corregedoria é órgão de controle INTERNO. O controle externo da atividade policial é atribuição constitucional do Ministério Público (art. 129, VII, CF/88). As demais competências listadas constam expressamente no art. 18.",
    art: "Art. 18",
  },
  {
    id: 16,
    tema: "Estrutura Organizacional",
    dif: "media",
    prob: "alta",
    enunc: "Todos os procedimentos administrativos e criminais instaurados contra servidores policiais civis deverão ser comunicados ao Conselho Superior da Polícia Civil. Essa comunicação é:",
    ops: [
      "Obrigatória apenas na conclusão do procedimento, garantindo o sigilo durante a investigação.",
      "Obrigatória apenas na instauração, incumbindo ao Delegado Geral decidir sobre comunicações posteriores.",
      "Facultativa, a critério da autoridade disciplinar, conforme a gravidade do caso.",
      "Obrigatória tanto na instauração quanto na conclusão dos respectivos procedimentos.",
      "Obrigatória somente quando houver proposta de pena de demissão ou cassação de aposentadoria.",
    ],
    corr: 3,
    com: "O parágrafo único do art. 18 é taxativo: os procedimentos 'serão obrigatoriamente comunicados ao Conselho Superior de Polícia Civil, quando da instauração e da conclusão dos respectivos procedimentos.' A comunicação é dupla (instauração + conclusão) e obrigatória.",
    art: "Art. 18, parágrafo único",
  },
  {
    id: 17,
    tema: "Estrutura Organizacional",
    dif: "baixa",
    prob: "alta",
    enunc: "O cargo de Corregedor-Geral de Polícia Civil, nos termos do art. 19 da Lei nº 883/2005:",
    ops: [
      "É de livre escolha e nomeação do Delegado Geral, aprovada pelo Conselho Superior.",
      "É privativo de Delegado de Polícia da Classe Especial, de livre escolha, nomeação e exoneração do Governador do Estado.",
      "É preenchido pelo Delegado mais antigo da carreira, por critério de antiguidade.",
      "Pode ser exercido por qualquer servidor policial civil de cargo efetivo, indicado pelo Conselho Superior.",
      "Exige aprovação por maioria absoluta do Conselho Superior de Polícia Civil.",
    ],
    corr: 1,
    com: "Art. 19: 'O Corregedor-Geral de Polícia Civil, cargo privativo de Delegado de Polícia da Classe Especial da respectiva carreira, é de livre escolha, nomeação e exoneração do Governador do Estado.'",
    art: "Art. 19",
  },
  {
    id: 18,
    tema: "Estrutura Organizacional",
    dif: "alta",
    prob: "alta",
    enunc: "Os Órgãos de Execução Programática da Polícia Civil são classificados em Funções Estratégicas e Funções Tático-Operacionais. Considere os Departamentos abaixo e identifique a classificação correta:\nI. Departamento de Inteligência\nII. Departamento de Polícia Administrativa\nIII. Departamento de Ações Especializadas\nIV. Departamentos das CIOSPs e Unidades de Polícia da Capital e do Interior",
    pergunta: "A classificação correta é:",
    ops: [
      "I=estratégica; II=tático-operacional; III=estratégica; IV=tático-operacional.",
      "I=estratégica; II=estratégica; III=tático-operacional; IV=tático-operacional.",
      "I=tático-operacional; II=estratégica; III=estratégica; IV=tático-operacional.",
      "I=estratégica; II=tático-operacional; III=tático-operacional; IV=estratégica.",
      "I=tático-operacional; II=tático-operacional; III=estratégica; IV=estratégica.",
    ],
    corr: 1,
    com: "Art. 24: Funções Estratégicas: (a) Dep. de Inteligência (I) e (b) Dep. de Polícia Administrativa (II). Funções Tático-Operacionais: (a) Dep. de Ações Especializadas (III) e (b) Dep. das CIOSPs e Unidades Policiais (IV).",
    art: "Art. 24",
  },
  {
    id: 19,
    tema: "Estrutura Organizacional",
    dif: "media",
    prob: "alta",
    enunc: "Conforme o art. 27, §1º da Lei nº 883/2005, consideram-se ações especializadas aquelas:",
    ops: [
      "Realizadas por equipes multidisciplinares com participação do Ministério Público.",
      "Referentes ao tipo criminal ou relativas ao tipo de operações táticas, em que se dá o emprego direto da força legítima e proporcional ao ato de violência que se enfrenta.",
      "Executadas exclusivamente pelo Departamento de Inteligência da Polícia Civil.",
      "Realizadas em conjunto com a Polícia Militar nas operações de combate ao crime organizado.",
      "Que envolvam investigação de crimes financeiros e de colarinho branco.",
    ],
    corr: 1,
    com: "O art. 27, §1º define: 'Consideram-se ações especializadas, as referentes ao tipo criminal ou relativas ao tipo de operações táticas, em que se dá o emprego direto da força legítima e proporcional ao ato de violência que se enfrenta.' Conceito cobrado na última prova PC-AP.",
    art: "Art. 27, §1º",
  },
  {
    id: 20,
    tema: "Provimento — Requisitos",
    dif: "media",
    prob: "alta",
    enunc: "São requisitos básicos para investidura em cargo policial civil, conforme o art. 29 da Lei nº 883/2005, EXCETO:",
    ops: [
      "Ser brasileiro.",
      "Estar no gozo dos direitos políticos.",
      "Gozar de boa saúde física e mental, comprovada em inspeção médica oficial.",
      "Ter conduta social irrepreensível, comprovada idoneidade moral e não possuir antecedentes criminais.",
      "Ter, no mínimo, 21 (vinte e um) anos de idade.",
    ],
    corr: 4,
    com: "O art. 29, IV exige idade mínima de 18 anos — não 21. As demais alternativas reproduzem fielmente os incisos I (ser brasileiro), II (direitos políticos), V (saúde) e VI (conduta/idoneidade) do art. 29.",
    art: "Art. 29",
  },
  {
    id: 21,
    tema: "Provimento — Requisitos",
    dif: "media",
    prob: "alta",
    enunc: "Quanto aos requisitos específicos por cargo, a Lei nº 883/2005 determina que o diploma de Bacharel em Direito para o cargo de Delegado de Polícia deve ser apresentado:",
    ops: [
      "No ato da posse no cargo.",
      "No ato da inscrição no concurso público.",
      "No ato da nomeação, antes da assinatura do ato pelo Governador.",
      "Após o Curso de Formação, como condição para a conclusão do processo seletivo.",
      "A qualquer tempo antes do início do exercício, desde que no prazo de 30 dias da nomeação.",
    ],
    corr: 1,
    com: "O art. 29, §1º dispõe: 'O cargo de Delegado de Polícia é privativo de possuidor de diploma de curso superior de Bacharel em Direito, exigindo-se no ato da inscrição no concurso a apresentação do respectivo diploma.' Para Agente e Oficial, o diploma de nível superior é exigido no ato da posse (§2º).",
    art: "Art. 29, §1º",
  },
  {
    id: 22,
    tema: "Provimento — Concurso",
    dif: "alta",
    prob: "alta",
    enunc: "O concurso público para ingresso nas carreiras policiais civis será realizado em duas etapas. A matrícula no Curso de Formação Policial, segunda etapa, está condicionada à aprovação, na ordem, nos seguintes exames, todos de caráter eliminatório:",
    ops: [
      "Prova dissertativa, exame físico e avaliação psicológica.",
      "Exame de higidez e aptidão física, exame psicológico de caráter objetivo e exame de investigação social.",
      "Exame médico, avaliação de antecedentes e prova oral perante banca.",
      "Exame psicológico, exame toxicológico e exame de saúde ocupacional.",
      "Exame físico, avaliação de títulos e prova oral de Direito.",
    ],
    corr: 1,
    com: "O art. 32, §1º lista os exames para matrícula no Curso de Formação, todos eliminatórios: a) exame de higidez e aptidão física; b) exame psicológico, de caráter objetivo; c) exame de investigação social.",
    art: "Art. 32, §1º",
  },
  {
    id: 23,
    tema: "Provimento — Concurso",
    dif: "baixa",
    prob: "alta",
    enunc: "O concurso público para ingresso nas carreiras policiais civis do Estado do Amapá terá validade de:",
    ops: [
      "1 (um) ano, podendo ser prorrogado uma única vez por igual período.",
      "2 (dois) anos, podendo ser prorrogado uma única vez por igual período.",
      "2 (dois) anos, podendo ser prorrogado duas vezes por igual período.",
      "Validade indefinida, até que todos os aprovados sejam nomeados.",
      "3 (três) anos, improrrogável.",
    ],
    corr: 1,
    com: "O art. 34 é expresso: 'O concurso público terá validade de até 2 (dois) anos podendo ser prorrogado uma única vez, por igual período.' Validade máxima: 4 anos (2+2).",
    art: "Art. 34",
  },
  {
    id: 24,
    tema: "Provimento — Concurso",
    dif: "media",
    prob: "alta",
    enunc: "Para ingresso na carreira de Delegado de Polícia, além das exigências da primeira etapa do concurso, a Lei nº 883/2005 exige:",
    ops: [
      "A realização de entrevista psicológica perante o Conselho Superior.",
      "A apresentação de título de pós-graduação em área jurídica.",
      "Prova oral de conhecimentos, com a participação da Ordem dos Advogados do Brasil — OAB.",
      "Prova dissertativa sobre temas de Direito Penal e Processo Penal.",
      "Estágio supervisionado de 6 meses na Delegacia Geral de Polícia Civil.",
    ],
    corr: 2,
    com: "O art. 60, §1º dispõe: 'Para ingresso na carreira de Delegado de Polícia, além das exigências constantes da primeira etapa, exigir-se-á prova oral de conhecimentos, com a participação da Ordem dos Advogados do Brasil — OAB.' Exigência exclusiva da carreira de Delegado.",
    art: "Art. 60, §1º",
  },
  {
    id: 25,
    tema: "Provimento — Curso de Formação",
    dif: "media",
    prob: "alta",
    enunc: "O aluno matriculado no Curso de Formação Policial Profissional fará jus, a título de bolsa mensal:",
    ops: [
      "Ao subsídio integral do cargo para o qual concorre.",
      "Ao valor correspondente a 50% do subsídio inicial da respectiva carreira.",
      "Ao valor correspondente a 75% do subsídio inicial da respectiva carreira.",
      "Ao recebimento de diárias, sem vínculo empregatício com o Estado.",
      "Ao valor fixado por ato do Delegado Geral, proporcional à carga horária do curso.",
    ],
    corr: 1,
    com: "O art. 36 dispõe: 'A contar da matrícula no Curso de Formação Policial Profissional, após ser aprovado em todas as fases da primeira etapa do concurso para ingresso na carreira policial civil, o aluno fará jus a título de bolsa mensal, de valor correspondente a 50% (cinquenta por cento) do subsídio inicial da respectiva carreira.'",
    art: "Art. 36",
  },
  {
    id: 26,
    tema: "Provimento — Curso de Formação",
    dif: "media",
    prob: "media",
    enunc: "O candidato que for servidor do Estado e estiver matriculado no Curso de Formação Policial:",
    ops: [
      "Continuará a exercer cumulativamente seu cargo de origem com o curso.",
      "Ficará afastado do cargo de origem e poderá optar pela bolsa ou pelo subsídio e vantagens do seu cargo.",
      "Perceberá obrigatoriamente apenas a bolsa do curso, sem qualquer remuneração do cargo de origem.",
      "Será automaticamente exonerado do cargo de origem a partir da matrícula.",
      "Receberá tanto a bolsa quanto a remuneração do cargo de origem.",
    ],
    corr: 1,
    com: "O art. 37 prevê que o candidato servidor 'ficará afastado do exercício do respectivo cargo, durante o curso, caso em que poderá optar pela bolsa ou pelo subsídio e vantagens do seu cargo, emprego ou função.' O parágrafo único determina que o tempo do curso conta para todos os efeitos legais da carreira.",
    art: "Art. 37",
  },
  {
    id: 27,
    tema: "Provimento — Posse e Exercício",
    dif: "media",
    prob: "alta",
    enunc: "A posse no cargo policial civil deverá ocorrer no prazo de:",
    ops: [
      "15 dias da publicação do ato, prorrogável por igual período a pedido do interessado.",
      "30 dias da publicação do ato de provimento, prorrogável por igual período a pedido do interessado.",
      "30 dias da publicação do ato de provimento, improrrogável.",
      "60 dias da publicação do ato, prorrogável uma única vez.",
      "15 dias da publicação, improrrogável.",
    ],
    corr: 1,
    com: "Art. 41, §1º: 'A posse ocorrerá no prazo de 30 (trinta) dias contados da publicação do ato de provimento, prorrogável por igual período, a pedido do interessado.' Ultrapassado o prazo sem a posse, o ato de provimento será tornado sem efeito (§6º).",
    art: "Art. 41, §1º",
  },
  {
    id: 28,
    tema: "Provimento — Posse e Exercício",
    dif: "media",
    prob: "alta",
    enunc: "O candidato que, na data da publicação do ato de provimento, estiver em gozo de férias ou licença legalmente concedida:",
    ops: [
      "Deverá tomar posse no prazo normal de 30 dias, contados da publicação.",
      "Terá o prazo para a posse contado a partir do término do impedimento (licença, férias ou serviços obrigatórios como júri).",
      "Poderá requerer prorrogação ao Delegado Geral, que decidirá discricionariamente.",
      "Perde o direito à nomeação, devendo aguardar nova convocação.",
      "Deverá nomear procurador para tomar posse durante o período de impedimento.",
    ],
    corr: 1,
    com: "O art. 41, §2º define que, nos casos de licença prevista em lei, férias ou júri/serviços obrigatórios, 'o prazo será contado do término de qualquer um dos seguintes impedimentos'. O prazo não corre durante o impedimento.",
    art: "Art. 41, §2º",
  },
  {
    id: 29,
    tema: "Provimento — Posse e Exercício",
    dif: "media",
    prob: "media",
    enunc: "A posse no cargo policial civil, nos termos da Lei nº 883/2005:",
    ops: [
      "Coincide com o início do exercício, sendo ambos um único ato.",
      "Pode ser realizada mediante procuração específica e é ato solene que compreende juramento, assinatura do termo, recebimento da carteira, distintivo, colete, arma e equipamentos.",
      "É ato meramente declaratório, sem formalidades solenes.",
      "Deve ser realizada obrigatoriamente de forma pessoal, vedada a procuração.",
      "É presidida pelo Delegado Geral de Polícia Civil.",
    ],
    corr: 1,
    com: "A posse é ato solene (art. 42): juramento, assinatura do termo, recebimento da carteira, distintivo, colete, arma e equipamentos. O §3º do art. 41 permite a posse mediante procuração específica.",
    art: "Art. 42",
  },
  {
    id: 30,
    tema: "Estágio Probatório",
    dif: "alta",
    prob: "alta",
    enunc: "O estágio probatório do servidor policial civil tem duração de:",
    ops: [
      "2 (dois) anos, durante os quais serão apurados assiduidade, disciplina, capacidade de iniciativa, produtividade e responsabilidade.",
      "3 (três) anos, durante os quais serão apurados assiduidade, disciplina, capacidade de iniciativa, produtividade e responsabilidade.",
      "2 (dois) anos, avaliando-se exclusivamente assiduidade e disciplina.",
      "3 (três) anos, avaliando-se apenas produtividade e responsabilidade.",
      "1 (um) ano, prorrogável por igual período a critério do Delegado Geral.",
    ],
    corr: 1,
    com: "O art. 45 estabelece estágio probatório de 3 anos, com avaliação de: assiduidade (I), disciplina (II), capacidade de iniciativa (III), produtividade (IV) e responsabilidade (V). Cuidado: a CF/88 prevê estágio de 3 anos para estabilidade, mas algumas leis antigas previam 2 anos.",
    art: "Art. 45",
  },
]

export const temas = [
  "Princípios Institucionais",
  "Direitos e Deveres",
  "Atribuições da Polícia Civil",
  "Estrutura Organizacional",
  "Provimento — Requisitos",
  "Provimento — Concurso",
  "Provimento — Curso de Formação",
  "Provimento — Posse e Exercício",
  "Estágio Probatório",
]
